### ISSUE TITLE
multihit database conflict

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteUploader#5]
Filtering on  multihitID=1014 I got

multihitID sampleID position chr strand
1014    68  319757  chr5_h2_hap1    -
1014    67  507396  chr17_random    -
1014    67  515377  chr17_random    -
1014    67  520266  chr17_random    -
1014    67  526414  chr17_random    -
1014    67  555352  chr17_random    +
1014    69  1874165 chr6_random -
1014    67  2608573 chr17_random    -
1014    64  3657207 chr6_qbl_hap2   +
1014    64  3849289 chr6_cox_hap1   +
1014    63  29956509    chr16   +
1014    63  32207527    chr1    +
1014    64  32550328    chr6    +
1014    62  37413562    chr7    -
1014    63  37870891    chr19   -
1014    67  38821755    chr17   -
1014    63  48892932    chr12   -
1014    63  54600289    chrX    +
1014    63  56798235    chr17   +
1014    66  57741533    chrY    +
1014    68  68861004    chr5    -
1014    63  73204332    chr9    -
1014    63  88408320    chr12   -
1014    63  91456639    chr12   +
1014    62  106338254   chr10   -
1014    70  109826340   chr2    -
1014    70  110852608   chr2    +
1014    66  154882333   chrX    +
1014    69  157988060   chr6    -
1014    65  159810682   chr1    -
1014    65  159892522   chr1    -
1014    63  226276698   chr1    +

**Comment by yhwu** [comment]
I think at some point the ID numbers got messed up.

multihitID sampleID position chr strand
179 16  195117218   chr1    +
179 16  199473137   chr1    +
179 16  207069354   chr2    -
179 16  214250971   chr2    -
179 16  223381311   chr1    +
180 16  7324234 chrY    +
180 16  115259160   chr8    +
181 16  4413685 chr6_qbl_hap2   -
181 16  4607652 chr6_cox_hap1   -
181 16  33335495    chr6    -
61  17  1717821 chr6_qbl_hap2   +
61  17  1919527 chr6_cox_hap1   +
61  17  30578935    chr6    +
62  17  1726372 chr6_qbl_hap2   +
62  17  1928080 chr6_cox_hap1   +
62  17  30587493    chr6    +
63  17  50015405    chr5    +

**Comment by anatolydryga** [comment]
we should pay special attention to cases like that 
that is a clear violation of ACID principle

https://en.wikipedia.org/?title=ACID

**Comment by yhwu** [comment]
got it, caused by  `length(multihitPositions)`, should have been `nrow()`
